---

- hosts: all
  become: true
  tasks:

  - name: installing packages
    dnf:
      name: 
        - httpd
        - php
      state: latest
      update_cache: yes
    when: anisble_distribution == "CentOS"

