---
### 
- hosts: all
  become: true
  pre_tasks:

  - name: installing updates for CentOS
    tags: always
    dnf:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "CentOS"

  - name: installing updates for Ubuntu
    tags: always
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

### 

- hosts: web_servers
  become: true
  tasks:

  - name: installing apache and php packages for CentOS
    tags: apache,apache2,centos
    dnf:
      name: 
        - httpd
        - php
      state: latest
    when: ansible_distribution == "CentOS"

### 

- hosts: db_servers
  become: true
  tasks:

  - name: installing mariadb packages for CentOS
    tags: db,mariadb,centos
    dnf:
      name: mariadb
      state: latest
    when: ansible_distribution == "CentOS"

### 

- hosts: file_servers
  become: true
  tasks:

  - name: installing samba packages for CentOS
    tags: samba
    dnf:
      name: samba
      state: latest
    when: ansible_distribution == "CentOS"
