---
### 
- hosts: all
  become: true
  pre_tasks:

  - name: installing updates for CentOS
    tags: always
    dnf:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "CentOS"

  - name: installing updates for Ubuntu
    tags: always
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

- hosts: all
  become: true
  tasks:

  - name: create simone user
    tags: always
    user:
      name: simone
      group: root

  - name: add shh key for simone
    tags: always
    authorized_key:
      user: simone
      key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAII6hsldeVmgehs19iTZazuXQrFKbScvs4vAQaLs9Lb55 ansible-only-testing"

  - name: add sudoers file for simone
    tags: always
    copy:
      src: sudoer-simone
      dest: /etc/sudoers.d/simone
      owner: root
      group: root
      mode: 0440

- hosts: workstations
  become: true
  tasks:

  - name: install unzip
    package:
      name: unzip

  - name: install terraform
    unarchive:
      src: https://releases.hashicorp.com/terraform/0.12.28/terraform_0.12.28_linux_amd64.zip
      dest: /usr/local/bin
      remote_src: yes
      mode: 755
      owner: root
      group: root

### 

- hosts: web_servers
  become: true
  tasks:

  - name: installing apache and php packages for CentOS
    tags: apache,apache2,centos
    dnf:
      name: 
        - httpd
        - php
      state: latest
    when: ansible_distribution == "CentOS"

  - name: start httpd (CentOS)
    tags: apache,centos,httpd
    service:
      name: httpd
      state: started
      enabled: yes
    when: ansible_distribution == "CentOS"

  - name: copy default html file for site
    tags: apache,apache2,httpd
    copy:
      src: default-site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644

### 

- hosts: db_servers
  become: true
  tasks:

  - name: installing mariadb packages for CentOS
    tags: db,mariadb,centos
    dnf:
      name: mariadb
      state: latest
    when: ansible_distribution == "CentOS"

### 

- hosts: file_servers
  become: true
  tasks:

  - name: installing samba packages for CentOS
    tags: samba
    dnf:
      name: samba
      state: latest
    when: ansible_distribution == "CentOS"
